### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Sherler** [TuGraph-family/tugraph-db-browser#23]
hello there，
I was trying to build this project locally, but it's not as easy as your doc says.
here is the first problem:
```bash
(base) PS E:\projects\tugraph-db-browser> yarn run bootstrap
Internal Error: tugraph-db-browser@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (C:\Users\georg\.yarn\releases\yarn-3.6.3.cjs:435:5145)
    at kf.getCandidates (C:\Users\georg\.yarn\releases\yarn-3.6.3.cjs:391:1264)
    at C:\Users\georg\.yarn\releases\yarn-3.6.3.cjs:439:8033
    at df (C:\Users\georg\.yarn\releases\yarn-3.6.3.cjs:390:11070)
    at ge (C:\Users\georg\.yarn\releases\yarn-3.6.3.cjs:439:8013)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async io (C:\Users\georg\.yarn\releases\yarn-3.6.3.cjs:390:10398)
    at async C:\Users\georg\.yarn\releases\yarn-3.6.3.cjs:439:8545
    at async ti.startProgressPromise (C:\Users\georg\.yarn\releases\yarn-3.6.3.cjs:390:47579)
(base) PS E:\projects\tugraph-db-browser> 
```

so I run this command:
```bash
yarn install
yarn run bootstrap
```
Still, it ends with errors:
![image](https://github.com/TuGraph-family/tugraph-db-browser/assets/11971198/41835e34-c37f-4e48-88a4-0421feb705fd)

And this
![image](https://github.com/TuGraph-family/tugraph-db-browser/assets/11971198/e8e4b2b2-b9b4-45f3-a705-1a2365c7f9f9)

I wonder if there is something I missed.

**Comment by baizn** [comment]
From the error message, it should be that the nodejs version is too high. It is recommended to change the nodejs version to 16 or below.
